// The content of this file was generated by IBM Cloud
// Do not modify it as it might get overridden
module.exports = function (app) {

    require('./public')(app);

    require('./health')(app);

    require('./test')(app);

    require('./articles')(app);

    require('./project')(app);

    require('./internalnews')(app);

    require('./competition')(app);

    require('./complains')(app);

    require('./laws')(app);

    require('./globalsearch')(app);

    require('./books')(app);

    require('./offices')(app);
};  